services:
  - type: web
    name: bitpay-websocket
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://your-vercel-app.vercel.app
